// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9VzI4RzdmHpL0tloJIH3d0eQjrKCPtpQ',
    appId: '1:589120674562:web:9db2aa8aa7e08e28d8801b',
    messagingSenderId: '589120674562',
    projectId: 'beauty-app-7e7aa',
    authDomain: 'beauty-app-7e7aa.firebaseapp.com',
    storageBucket: 'beauty-app-7e7aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSQVCybB8P_EytHlHn_6pEWYhFVreLWDA',
    appId: '1:589120674562:android:7e1a6bcc92193029d8801b',
    messagingSenderId: '589120674562',
    projectId: 'beauty-app-7e7aa',
    storageBucket: 'beauty-app-7e7aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHycnZVsKUbMYkAUJ06qAnNMMSA5AqQ9c',
    appId: '1:589120674562:ios:461b0a0e59bbe183d8801b',
    messagingSenderId: '589120674562',
    projectId: 'beauty-app-7e7aa',
    storageBucket: 'beauty-app-7e7aa.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHycnZVsKUbMYkAUJ06qAnNMMSA5AqQ9c',
    appId: '1:589120674562:ios:461b0a0e59bbe183d8801b',
    messagingSenderId: '589120674562',
    projectId: 'beauty-app-7e7aa',
    storageBucket: 'beauty-app-7e7aa.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9VzI4RzdmHpL0tloJIH3d0eQjrKCPtpQ',
    appId: '1:589120674562:web:0bd7f484b08bfe7ad8801b',
    messagingSenderId: '589120674562',
    projectId: 'beauty-app-7e7aa',
    authDomain: 'beauty-app-7e7aa.firebaseapp.com',
    storageBucket: 'beauty-app-7e7aa.firebasestorage.app',
  );
}
